name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: jonas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jonas/cloudsystemenProject
            git pull origin main
            cd lab-state-loading-indicator
            docker compose up -d --build
